name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    runs-on: ${{ matrix.os }}
    steps: 

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}
  
      - name: install modules
        run: npm install 

      - name: build production project
        run: npm run build:prod 

      - name: typescript linter
        run: npm run lint:ts

      - name: scss linter
        run: npm run lint:scss

      - name: screen tests
        run: npm run test:ui    
      - name: unit tests
        run: npm run test:unit
