name: CI

# Set on which events you want run the actions.
# In this case the workflow will run on push for master and on pull request for master and develop branches
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  integration:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12]
    runs-on: ${{ matrix.os }}
    steps: 

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}
  
      - name: install modules
        run: npm install 

      - name: build production project
        run: npm run build:prod 

      - name: typescript linter
        run: npm run lint:ts

      - name: scss linter
        run: npm run lint:scss

      - name: screen tests
        run: npm run test:ui    
      - name: unit tests
        run: npm run test:unit
