name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps: 
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: install modules
        run: npm install 

      - name: typescript linter
        run: npm run lint:ts

      - name: scss linter
        run: npm run lint:scss

      - name: screen tests
        run: npm run test:ui    
      - name: unit tests
        run: npm run test:unit

      - name: build production project
        run: npm run build:prod 
